## Import Necessary Libraries

In [35]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report

## Data Collection and understanding

In [4]:
breast_cancer_data = datasets.load_breast_cancer()
breast_cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [7]:
breast_cancer_df = pd.DataFrame(data= breast_cancer_data["data"],columns = breast_cancer_data["feature_names"])

In [8]:
breast_cancer_df

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [9]:
## Add the target column

breast_cancer_df["Target"] = breast_cancer_data["target"]

In [10]:
breast_cancer_df

     mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension  Target
0          17.99         10.38          122.80  ...          0.4601                  0.11890       0
1          20.57         17.77          132.90  ...          0.2750                  0.08902       0
2          19.69         21.25          130.00  ...          0.3613                  0.08758       0
3          11.42         20.38           77.58  ...          0.6638                  0.17300       0
4          20.29         14.34          135.10  ...          0.2364                  0.07678       0
..           ...           ...             ...  ...             ...                      ...     ...
564        21.56         22.39          142.00  ...          0.2060                  0.07115       0
565        20.13         28.25          131.20  ...          0.2572                  0.06637       0
566        16.60         28.08          108.30  ...          0.2218                  0.07820       0
567        20.60         29.33          140.10  ...          0.4087                  0.12400       0
568         7.76         24.54           47.92  ...          0.2871                  0.07039       1

[569 rows x 31 columns]

In [11]:
breast_cancer_df["Target"].value_counts()

Target
1    357
0    212
Name: count, dtype: int64

In [17]:
print(breast_cancer_data.DESCR)

## in here it is mentioned as "Class Distribution: 212 - Malignant, 357 - Benign"

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - class:
            - WDBC-Malignant
            - WDBC-Benign

:Summary Statistics:

===================================== ====== ======
                                        Min    Max
===================================== ====== ======
radius (mean):                        6.981  28.11
texture (mean):                       9.71   39.28
perimeter (mean):                     43.79  188.5
area (mean):                          143.5  2501.0
smoothness (mean):                    0.053  0.163
compactness (mean):                   0.019  0.345
concavity (mean):                     0.0    0.427
concave points (mean):                0.0    0.201
symmetry (mean):                      0.106  0.304
fractal dimension (mean):             0.05   0.097
radius (standard error):              0.112  2.873
texture (standard error):             0.36   4.885
perimeter (standard error):           0.757  21.98
area (standard error):                6.802  542.2
smoothness (standard error):          0.002  0.031
compactness (standard error):         0.002  0.135
concavity (standard error):           0.0    0.396
concave points (standard error):      0.0    0.053
symmetry (standard error):            0.008  0.079
fractal dimension (standard error):   0.001  0.03
radius (worst):                       7.93   36.04
texture (worst):                      12.02  49.54
perimeter (worst):                    50.41  251.2
area (worst):                         185.2  4254.0
smoothness (worst):                   0.071  0.223
compactness (worst):                  0.027  1.058
concavity (worst):                    0.0    1.252
concave points (worst):               0.0    0.291
symmetry (worst):                     0.156  0.664
fractal dimension (worst):            0.055  0.208
===================================== ====== ======

:Missing Attribute Values: None

:Class Distribution: 212 - Malignant, 357 - Benign

:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

:Donor: Nick Street

:Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. dropdown:: References

  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
    San Jose, CA, 1993.
  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
    prognosis via linear programming. Operations Research, 43(4), pages 570-577,
    July-August 1995.
  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
    163-171.

## 3. Data Preparation

In [18]:
breast_cancer_df.shape

(569, 31)

In [19]:
breast_cancer_df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [21]:
breast_cancer_df.describe()

       mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension      Target
count   569.000000    569.000000      569.000000  ...      569.000000               569.000000  569.000000
mean     14.127292     19.289649       91.969033  ...        0.290076                 0.083946    0.627417
std       3.524049      4.301036       24.298981  ...        0.061867                 0.018061    0.483918
min       6.981000      9.710000       43.790000  ...        0.156500                 0.055040    0.000000
25%      11.700000     16.170000       75.170000  ...        0.250400                 0.071460    0.000000
50%      13.370000     18.840000       86.240000  ...        0.282200                 0.080040    1.000000
75%      15.780000     21.800000      104.100000  ...        0.317900                 0.092080    1.000000
max      28.110000     39.280000      188.500000  ...        0.663800                 0.207500    1.000000

[8 rows x 31 columns]

In [22]:
breast_cancer_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int64
dtype: object

## 4. Model Building

In [25]:
X = breast_cancer_df.drop("Target", axis =1)
X

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [27]:
y = breast_cancer_df["Target"]
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: Target, Length: 569, dtype: int64

In [41]:
from sklearn.preprocessing import MinMaxScaler

minmax_scale = MinMaxScaler()

Scaled_X = minmax_scale.fit_transform(X,y)

scaled_X = pd.DataFrame(Scaled_X, columns = breast_cancer_data["feature_names"])
scaled_X

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0       0.521037      0.022658        0.545989  ...              0.912027        0.598462                 0.418864
1       0.643144      0.272574        0.615783  ...              0.639175        0.233590                 0.222878
2       0.601496      0.390260        0.595743  ...              0.835052        0.403706                 0.213433
3       0.210090      0.360839        0.233501  ...              0.884880        1.000000                 0.773711
4       0.629893      0.156578        0.630986  ...              0.558419        0.157500                 0.142595
..           ...           ...             ...  ...                   ...             ...                      ...
564     0.690000      0.428813        0.678668  ...              0.761512        0.097575                 0.105667
565     0.622320      0.626987        0.604036  ...              0.559450        0.198502                 0.074315
566     0.455251      0.621238        0.445788  ...              0.487285        0.128721                 0.151909
567     0.644564      0.663510        0.665538  ...              0.910653        0.497142                 0.452315
568     0.036869      0.501522        0.028540  ...              0.000000        0.257441                 0.100682

[569 rows x 30 columns]

In [42]:
scaled_X.mean(), scaled_X.std()

(mean radius                0.338222
 mean texture               0.323965
 mean perimeter             0.332935
 mean area                  0.216920
 mean smoothness            0.394785
 mean compactness           0.260601
 mean concavity             0.208058
 mean concave points        0.243137
 mean symmetry              0.379605
 mean fractal dimension     0.270379
 radius error               0.106345
 texture error              0.189324
 perimeter error            0.099376
 area error                 0.062636
 smoothness error           0.181119
 compactness error          0.174439
 concavity error            0.080540
 concave points error       0.223454
 symmetry error             0.178143
 fractal dimension error    0.100193
 worst radius               0.296663
 worst texture              0.363998
 worst perimeter            0.283138
 worst area                 0.170906
 worst smoothness           0.404138
 worst compactness          0.220212
 worst concavity            0.217403
 worst concave points       0.393836
 worst symmetry             0.263307
 worst fractal dimension    0.189596
 dtype: float64,
 mean radius                0.166787
 mean texture               0.145453
 mean perimeter             0.167915
 mean area                  0.149274
 mean smoothness            0.126967
 mean compactness           0.161992
 mean concavity             0.186785
 mean concave points        0.192857
 mean symmetry              0.138456
 mean fractal dimension     0.148702
 radius error               0.100421
 texture error              0.121917
 perimeter error            0.095267
 area error                 0.084967
 smoothness error           0.102067
 compactness error          0.134498
 concavity error            0.076227
 concave points error       0.116884
 symmetry error             0.116316
 fractal dimension error    0.091417
 worst radius               0.171940
 worst texture              0.163813
 worst perimeter            0.167352
 worst area                 0.139932
 worst smoothness           0.150779
 worst compactness          0.152649
 worst concavity            0.166633
 worst concave points       0.225884
 worst symmetry             0.121954
 worst fractal dimension    0.118466
 dtype: float64)

In [43]:
## All the mean and std is between 0 to 1

scaled_X.describe()

       mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
count   569.000000    569.000000      569.000000  ...            569.000000      569.000000               569.000000
mean      0.338222      0.323965        0.332935  ...              0.393836        0.263307                 0.189596
std       0.166787      0.145453        0.167915  ...              0.225884        0.121954                 0.118466
min       0.000000      0.000000        0.000000  ...              0.000000        0.000000                 0.000000
25%       0.223342      0.218465        0.216847  ...              0.223127        0.185098                 0.107700
50%       0.302381      0.308759        0.293345  ...              0.343402        0.247782                 0.163977
75%       0.416442      0.408860        0.416765  ...              0.554639        0.318155                 0.242949
max       1.000000      1.000000        1.000000  ...              1.000000        1.000000                 1.000000

[8 rows x 30 columns]

In [44]:
X_train,X_test,y_train,y_test = train_test_split(scaled_X,y, test_size=0.2,random_state=12,shuffle=True, stratify=y)

In [45]:
X_train,X_test,y_train,y_test

(     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
 494     0.292442      0.366250        0.278281  ...              0.144158        0.221171                 0.126263
 97      0.132803      0.345959        0.126598  ...              0.081821        0.072738                 0.228519
 528     0.329358      0.117010        0.321471  ...              0.348797        0.117288                 0.114719
 359     0.116191      0.291173        0.110773  ...              0.173608        0.175241                 0.172635
 352     0.887359      0.262090        0.901182  ...              0.947079        0.418884                 0.217172
 ..           ...           ...             ...  ...                   ...             ...                      ...
 256     0.594870      0.644572        0.620621  ...              0.667010        0.246994                 0.298177
 246     0.294335      0.261075        0.278764  ...              0.170790        0.236941                 0.111111
 82      0.863221      0.514034        0.882524  ...              0.985223        0.155726                 0.328348
 268     0.278716      0.219817        0.266671  ...              0.198625        0.401932                 0.102191
 492     0.521984      0.366926        0.515583  ...              0.511684        0.332348                 0.139118

 [455 rows x 30 columns],
      mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
 244     0.587770      0.466351        0.589524  ...              0.537457        0.267100                 0.138397
 451     0.596763      0.517078        0.579849  ...              0.503780        0.143505                 0.038502
 115     0.234228      0.399729        0.226246  ...              0.249038        0.172088                 0.199200
 391     0.082967      0.241123        0.079331  ...              0.000000        0.173467                 0.220451
 145     0.232808      0.167061        0.237164  ...              0.207629        0.229056                 0.318510
 ..           ...           ...             ...  ...                   ...             ...                      ...
 432     0.624686      0.332432        0.622003  ...              0.746735        0.289178                 0.168634
 131     0.401297      0.330402        0.400180  ...              0.520275        0.250739                 0.164961
 447     0.370060      0.268854        0.359961  ...              0.285498        0.401143                 0.116818
 124     0.302381      0.225905        0.292378  ...              0.308522        0.095210                 0.139315
 28      0.393724      0.526209        0.405017  ...              0.695533        0.485314                 0.286764

 [114 rows x 30 columns],
 494    1
 97     1
 528    1
 359    1
 352    0
       ..
 256    0
 246    1
 82     0
 268    1
 492    0
 Name: Target, Length: 455, dtype: int64,
 244    0
 451    0
 115    1
 391    1
 145    1
       ..
 432    0
 131    0
 447    1
 124    1
 28     0
 Name: Target, Length: 114, dtype: int64)

## 5. Model Building

In [47]:
dt_model = DecisionTreeClassifier(criterion='gini', max_depth= 5,class_weight={0:2,1:1})

dt_model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight={0: 2, 1: 1}, max_depth=5)

## 6. Model training

In [51]:
pred_train = dt_model.predict(X_train)
pred_train

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

## 7. Model Testing

In [58]:
pred_test = dt_model.predict(X_test)
pred_test

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0])

## 8. Model Evaluation

#### For Training Data

In [63]:
print(confusion_matrix(y_pred_train,y_train))

[[169   1]
 [  1 284]]

In [64]:
print(classification_report(y_pred_train,y_train))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       170
           1       1.00      1.00      1.00       285

    accuracy                           1.00       455
   macro avg       1.00      1.00      1.00       455
weighted avg       1.00      1.00      1.00       455

#### For Test Data

In [62]:
print(confusion_matrix(pred_test,y_test))

[[38  6]
 [ 4 66]]

In [61]:
print(classification_report(pred_test,y_test))

              precision    recall  f1-score   support

           0       0.90      0.86      0.88        44
           1       0.92      0.94      0.93        70

    accuracy                           0.91       114
   macro avg       0.91      0.90      0.91       114
weighted avg       0.91      0.91      0.91       114

## 9. Model Deployement

In [65]:
from pickle import dump

In [66]:
dump(obj = scaled_X, file = open("min_max_data.pkl","wb"))

In [68]:
dump(obj = dt_model, file = open("mdt_model.pkl","wb"))